### ISSUE TITLE
I  can't access http://localhost:6080/crawler

### ISSUE THREAD

**Issue by Makwen1995** [scrapy-plugins/scrapy-jsonrpc#14]
# Can someone tell me how to use it? I modified the configuration according to the document, but I could not access http://localhost:6080/crawler....
**a part of "setting.py":**
JSONRPC_ENABLED = True
EXTENSIONS = {
    'scrapy_jsonrpc.webservice.WebService': 500,
}

i use python3.5,and scrapy 1.3.2
if you know the problem,could you please answer me?Thank you very much...

**Comment by redapple** [comment]
This plugin is unfortunately not Python 3 compatible. See #12

**Comment by redapple** [comment]
@swumqw , I can only suggest that you follow https://github.com/scrapy-plugins/scrapy-jsonrpc/issues/12 or help with porting scrapy-jsonrpc to Python 3
