### ISSUE TITLE
exceptions.TypeError: <scrapy.crawler.Crawler object at 0x0000000004681D30> is not JSON serializable

### ISSUE THREAD

**Issue by lcz1688** [scrapy-plugins/scrapy-jsonrpc#16]
on windows7，python2.7

**Comment by redapple** [comment]
How are you communicating with the RPC service?

**Comment by lcz1688** [comment]
I just send a http get request to http://localhost:6080/crawler

**Comment by redapple** [comment]
I believe you are misinterpreting how to use scrapy-jsonrpc. Please check https://github.com/scrapy-plugins/scrapy-jsonrpc/blob/master/example-client.py for an example of how to query the service.
