### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Usman995** [scrapy-plugins/scrapy-jsonrpc#23]
since I installed this to my project I've been getting 
![Screenshot 2021-05-12 at 23 08 33](https://user-images.githubusercontent.com/57040341/118050341-fb62c880-b376-11eb-92a4-f3ed6544eb90.png)

**Comment by Usman995** [comment]
how do I uninstall this package

**Comment by Gallaecio** [comment]
Closing in favor of https://github.com/scrapy-plugins/scrapy-jsonrpc/issues/12
