### ISSUE TITLE
how to install and enable in the scrapy project?

### ISSUE THREAD

**Issue by gamelife1314** [scrapy-plugins/scrapy-jsonrpc#5]
how to install and enable in the scrapy project?

**Comment by redapple** [comment]
@gamelife1314 ,
you can install the package in your environment via pip:

`pip install scrapy-jsonrpc`

Then, you need to add the extension to your scrapy project's `settings.py`

```
EXTENSIONS = {
    'scrapy_jsonrpc.webservice.WebService': 500,
}
```

and finally enabled the extensions with `JSONRPC_ENABLED=True` in your `settings.py` also.

Does this help?

**Comment by gamelife1314** [comment]
@redapple thank you!

**Comment by redapple** [comment]
You're welcome
