### ISSUE TITLE
log.msg has been deprecated

### ISSUE THREAD

**Issue by lucab0ni** [scrapy-plugins/scrapy-jsonrpc#8]
The logging of messages via log module is deprecated. Scrapy uses now the python logging module.

**Comment by robertodormepoco** [comment]
see af748b9e2f7f6eca30ab59918c1f40bb7d2c6d2a

**Comment by redapple** [comment]
Fixed in https://github.com/scrapy-plugins/scrapy-jsonrpc/pull/7
